version: "3"

services:
  db:
    image: mongo:latest
    networks: 
      - db
    ports:
      - 30000:27017
  server:
    build: .
    command: npm start
    environment:
      - ConnString=mongodb://db/blockchain
      - Difficulty=4
      - MonitoringTime=500
      - HelixUrl=http://143.107.145.18:1026/v2/entities/
      - HelixEntity=blockchain
      - Blockchain=http://143.107.145.28:8080/api/getBlocks
    networks: 
      - db
    ports:
      - 8080:8080
    depends_on: 
      - db

networks: 
  db:
    driver: bridge