version: "3"

services:
  db:
    image: mongo:latest
    networks: 
      - db
    ports:
      - 30000:27017
  server:
    build: .
    command: npm start
    networks: 
      - db
    ports:
      - 8080:8080
    depends_on: 
      - db

networks: 
  db:
    driver: bridge